### ISSUE TITLE
Issue with @Facets and @XmlJavaTypeAdapter

### ISSUE THREAD

**Issue by pellcorp** [whummer/jaxb-facets#24]
A fragment of my entity:

private BigDecimal salary;
    
    @XmlElement(name = "salary")
    @javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(com.pellcorp.jaxb.DecimalAdaptor.class)
    @javax.xml.bind.annotation.Facets(minInclusive="1000.1", maxInclusive="9999.2")
    public BigDecimal getSalary() {
        return salary;
    }

Decimal Adaptor is:

public class DecimalAdaptor extends XmlAdapter<String, BigDecimal> {
    @Override
    public String marshal(BigDecimal value) throws Exception {
        if (value == null) {
            return null;
        }
        
        return value.toPlainString();
    }

    @Override
    public BigDecimal unmarshal(String value) throws Exception {
        if (value == null) {
            return null;
        }
        
        CharSequence trimmed = WhiteSpaceProcessor.trim(value);
        
        if (trimmed.length() == 0) {
            return null;
        }
        
        try {
            return new BigDecimal(trimmed.toString());
        } catch (NumberFormatException e) {
            throw new NumberFormatException("Invalid decimal");
        }
    }
}

I get the following exception only where I am using the adaptor...

java.lang.RuntimeException: org.xml.sax.SAXParseException; cos-applicable-facets: Facet 'maxInclusive' is not allowed by type #AnonType_salaryPerson.
	at com.pellcorp.jaxb.JaxbTest.getSchema(JaxbTest.java:172)
	at com.pellcorp.jaxb.JaxbTest.setup(JaxbTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.xml.sax.SAXParseException; cos-applicable-facets: Facet 'maxInclusive' is not allowed by type #AnonType_salaryPerson.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:347)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4166)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4145)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.reportSchemaError(XSDAbstractTraverser.java:721)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDSimpleTypeTraverser.getSimpleType(XSDSimpleTypeTraverser.java:406)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDSimpleTypeTraverser.traverseLocal(XSDSimpleTypeTraverser.java:147)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:397)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseLocal(XSDElementTraverser.java:194)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseLocalElements(XSDHandler.java:3618)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:633)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:616)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:574)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:540)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:252)
	at com.pellcorp.jaxb.JaxbTest.getSchema(JaxbTest.java:169)
	... 16 more

**Comment by whummer** [comment]
Short answer: Add the type attribute to the @XmlElement annotation:
```
    @XmlElement(name = "salary", type = BigDecimal.class)
```

Explanation:

The adaptor uses generic type String, hence JAXB thinks the salary is of type String. Therefore, jaxb-facets creates a facet definition onto an element with base type xs:string (see below). Problem is that the xs:maxInclusive facet is not allowed on the type string. Hence, we need to ensure that base type is xs:decimal (which is achieved by explicitly setting the type, as above).

```
<xs:element minOccurs="0" name="salary">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxInclusive value="9999.2" />
            <xs:minInclusive value="1000.1" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
```

**Comment by pellcorp** [comment]
But the java field itself has BigDecimal as its type.  When the XSD gets generated with the Facet (but without the XmlAdaptor) all is fine.  It gets generated as described by you.

Its only when I try to add an adaptor that it crashes out.  In the end I worked around it by overriding the error handler of jaxb instead of trying to use a XmlMarshaller.  A better solution anyway.

I was just not sure if the changes made for the jaxb facets were causing the problems.
