### ISSUE TITLE
mvn clean install with empty repository

### ISSUE THREAD

**Issue by nilzao** [whummer/jaxb-facets#25]
My version:

    $ uname -a
    Linux nilspc 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ mvn -v
    Apache Maven 3.0.5
    Maven home: /usr/share/maven
    Java version: 1.7.0_75, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/jdk1.7.0_75/jre
    Default locale: pt_BR, platform encoding: UTF-8
    OS name: "linux", version: "3.13.0-46-generic", arch: "amd64", family: "unix"

with empty $HOME/.m2/repository

$ mvn clean compile

some errors to get dependencys, fixed testutils/pom.xml b/testutils/pom.xml

    diff --git a/testutils/pom.xml b/testutils/pom.xml
    index 25f45bd..0397d90 100644
    --- a/testutils/pom.xml
    +++ b/testutils/pom.xml
    @@ -4,11 +4,18 @@
         <artifactId>testutils</artifactId>
         <version>0.3</version>
     
    -	<parent>
    +	<properties>
    +                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    +                <maven.compiler.source>1.6</maven.compiler.source>
    +                <maven.compiler.target>1.6</maven.compiler.target>
    +	</properties>
    +
    +
    +       <parent>
              <groupId>at.ac.tuwien.infosys</groupId>
         	 <artifactId>jaxb-facets</artifactId>
         	 <version>2.2.7-facets-1.3.0</version>
    -    </parent>
    +        </parent>
         
         <dependencies>
             <dependency>
    @@ -56,7 +63,7 @@
     		<dependency>
     			<groupId>xerces</groupId>
     			<artifactId>xercesImpl</artifactId>
    -			<version>2.11.0-beta-140301</version>
    +			<version>2.11.0</version>
     		</dependency>
     
     		<dependency>
    @@ -128,4 +135,16 @@
     			<version>2.0.2</version>
     		</dependency>
         </dependencies>
    +
    +         <repositories>
    +                <repository>
    +                        <id>github-repo-releases</id>
    +                        <url>https://raw.github.com/whummer/jaxb-facets/master/releases</url>
    +                </repository>
    +            <repository>
    +                <id>infosys-repo-releases</id>
    +                <url>http://www.infosys.tuwien.ac.at/mvn</url>
    +            </repository>
    +        </repositories>
    +
     </project>

$ mvn clean test
fail on testValidateGeneratedXsd. I don't know what to do... so i commented the test

    diff --git a/jaxb-impl/src/test/java/at/ac/tuwien/infosys/jaxb/SchemaValidationTest.java b/jaxb-impl/src/test/java/
    index eb82911..e14e5b6 100644
    --- a/jaxb-impl/src/test/java/at/ac/tuwien/infosys/jaxb/SchemaValidationTest.java
    +++ b/jaxb-impl/src/test/java/at/ac/tuwien/infosys/jaxb/SchemaValidationTest.java
    @@ -33,7 +33,7 @@ public class SchemaValidationTest extends AbstractTestCase {
     
             cleanupServers();
         }
    -
    +/*
         @Test
         public void testValidateGeneratedXsd() throws Exception {
             String xml = getWsdlSchemaAsString(PersonService.class);
    @@ -52,5 +52,5 @@ public class SchemaValidationTest extends AbstractTestCase {
                 fail("Schema parsing error. See stack trace for details.");
             }
         }
    -
    +*/
     }

$mvn clean install
runs ok.

created a project just like this: https://github.com/whummer/jaxb-facets/issues/23 changing the version 2.2.6-facets-1.3.0 to 2.2.6-facets-1.3.1

    $ mvn clean compile
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building jaxb-facets-sandbox 0.0.1-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jaxb-facets-sandbox ---
    [INFO] Deleting /home/nils/workspaces/j2ee/jaxb-facets-sandbox/target
    [INFO] 
    [INFO] --- jaxb2-maven-plugin:1.6:schemagen (schemagen) @ jaxb-facets-sandbox ---
    Fev 25, 2015 2:56:57 PM at.ac.tuwien.infosys.jaxb.XmlSchemaEnhancer writeCustomOccurs
    ADVERTÊNCIA: Unable to get @MinOccurs annotation from type com.sun.xml.bind.v2.model.impl.TypeRefImpl@2199a025
    java.lang.RuntimeException: Unexpected type of property parent: jaxb.factets.sandbox.Boo
	    at at.ac.tuwien.infosys.jaxb.XmlSchemaEnhancer.getAnnotationOfProperty(XmlSchemaEnhancer.java:955)
	    at at.ac.tuwien.infosys.jaxb.XmlSchemaEnhancer.writeCustomOccurs(XmlSchemaEnhancer.java:499)
	    at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace$2.write(XmlSchemaGenerator.java:1178)
	    at com.sun.xml.bind.v2.schemagen.TreeWrapper.write(TreeWrapper.java:90)
	    at com.sun.xml.bind.v2.schemagen.Tree$Group.write(Tree.java:255)
	    at com.sun.xml.bind.v2.schemagen.Tree.write(Tree.java:138)
	    at com.sun.xml.bind.v2.schemagen.Tree.write(Tree.java:141)
	    at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace.writeClass(XmlSchemaGenerator.java:1039)
	    at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace.writeTo(XmlSchemaGenerator.java:721)
	    at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace.access$800(XmlSchemaGenerator.java:519)
	    at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator.write(XmlSchemaGenerator.java:501)
	    at com.sun.tools.xjc.api.impl.j2s.JAXBModelImpl.generateSchema(JAXBModelImpl.java:183)
	    at com.sun.tools.jxc.ap.SchemaGenerator.process(SchemaGenerator.java:115)
	    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	    at com.sun.tools.javac.main.Main.compile(Main.java:439)
	    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	    at com.sun.tools.jxc.SchemaGenerator$Runner.compile(SchemaGenerator.java:240)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:606)
	    at com.sun.tools.jxc.SchemaGenerator.run(SchemaGenerator.java:171)
	    at com.sun.tools.jxc.SchemaGenerator.run(SchemaGenerator.java:86)
	    at org.codehaus.mojo.jaxb2.AbstractSchemagenMojo.execute(AbstractSchemagenMojo.java:215)
	    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:606)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

    [INFO] 
    [INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ jaxb-facets-sandbox ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] Copying 0 resource
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jaxb-facets-sandbox ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 1 source file to /home/nils/workspaces/j2ee/jaxb-facets-sandbox/target/classes
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.048s
    [INFO] Finished at: Wed Feb 25 14:56:58 AMT 2015
    [INFO] Final Memory: 16M/157M
    [INFO] ------------------------------------------------------------------------

and the output is missing the @MinOccurs:
target/generated-resources/schemagen/schema1.xsd 

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <xs:schema version="1.0" targetNamespace="jaxb-sandbox" xmlns:xs="http://www.w3.org/2001/XMLSchema">

      <xs:complexType name="boo">
        <xs:sequence>
          <xs:element name="someNumber">
            <xs:simpleType>
              <xs:restriction base="xs:int"/>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:schema>

I will try with older versions, then comment here.

**Comment by nilzao** [comment]
with this commit a9bb684a7c55839e0bfde3c32c6e23e046000722

with empty $HOME/.m2/repository

$mvn clean install

runs good.

this https://github.com/whummer/jaxb-facets/issues/23

$mvn clean compile

same warning, but xsd with minInclusive

**Comment by whummer** [comment]
Thanks for reporting. Have you been able to resolve it, or are you still experiencing this issue?

**Comment by whummer** [comment]
Closing this ticket due to inactivity. Please feel free to re-open.
